# Generated by Django 5.0 on 2024-01-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Student', 'Estudiante'), ('Technical', 'Técnico')], default='Technical', max_length=10),
        ),
    ]
