# Generated by Django 5.0 on 2023-12-09 16:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('celular', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=50)),
                ('rol', models.CharField(choices=[('estudiante', 'Estudiante'), ('tecnico', 'Técnico')], max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouse', models.BooleanField()),
                ('teclado', models.BooleanField()),
                ('id_user_encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('id_comp_pert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.computadora')),
            ],
        ),
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('tipo', models.CharField(choices=[('ssd', 'SSD'), ('hdd', 'HDD')], max_length=10)),
                ('velocidad_escritura', models.IntegerField()),
                ('velocidad_lectura', models.IntegerField()),
                ('id_cpu_pert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.cpu')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('num_piso', models.IntegerField()),
                ('num_mesas', models.IntegerField()),
                ('num_sillas', models.IntegerField()),
                ('extintor', models.BooleanField()),
                ('basurero', models.BooleanField()),
                ('botiquin', models.BooleanField()),
                ('aire_acondicionado', models.BooleanField()),
                ('camara_seguiridad', models.BooleanField()),
                ('pizzara', models.BooleanField()),
                ('cortina_proyector', models.BooleanField()),
                ('id_user_encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='computadora',
            name='id_lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectores', to='user.laboratorio'),
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(default='', max_length=50)),
                ('resolucion', models.CharField(max_length=50)),
                ('pulgadas', models.IntegerField()),
                ('marca', models.CharField(max_length=50)),
                ('herz', models.CharField(blank=True, choices=[('60', '60'), ('120', '120'), ('144', '144')], max_length=10, null=True)),
                ('id_comp_pert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.computadora')),
            ],
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('generacion', models.IntegerField()),
                ('arquitectura', models.CharField(choices=[('x86', 'x86'), ('x64', 'x64'), ('X32', 'X32')], max_length=10)),
                ('velocidad', models.IntegerField()),
                ('nucleos', models.IntegerField()),
                ('hilos', models.IntegerField()),
                ('id_cpu_pert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.cpu')),
            ],
        ),
        migrations.CreateModel(
            name='Proyector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('id_lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('velocidad', models.IntegerField()),
                ('tipo', models.CharField(choices=[('ddr3', 'DDR3'), ('ddr4', 'DDR4')], max_length=10)),
                ('id_cpu_pert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.cpu')),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('id_computadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.computadora')),
                ('id_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('id_recomendacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.recomendacion')),
                ('id_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
