# Generated by Django 5.0 on 2023-12-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouse', models.BooleanField()),
                ('keyboard', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('type', models.CharField(choices=[('ssd', 'SSD'), ('hdd', 'HDD')], max_length=10)),
                ('write_speed', models.IntegerField()),
                ('read_speed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('floor_number', models.IntegerField()),
                ('table_number', models.IntegerField()),
                ('chair_number', models.IntegerField()),
                ('fire_extinguisher', models.BooleanField()),
                ('trash_can', models.BooleanField()),
                ('first_aid_kit', models.BooleanField()),
                ('air_conditioning', models.BooleanField()),
                ('security_camera', models.BooleanField()),
                ('whiteboard', models.BooleanField()),
                ('projector_screen', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='', max_length=50)),
                ('resolution', models.CharField(max_length=50)),
                ('inches', models.IntegerField()),
                ('brand', models.CharField(max_length=50)),
                ('herz', models.CharField(blank=True, choices=[('60', '60'), ('120', '120'), ('144', '144')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('generation', models.IntegerField()),
                ('architecture', models.CharField(choices=[('x86', 'x86'), ('x64', 'x64'), ('X32', 'X32')], max_length=10)),
                ('speed', models.IntegerField()),
                ('cores', models.IntegerField()),
                ('threads', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Projector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('type', models.CharField(choices=[('ddr3', 'DDR3'), ('ddr4', 'DDR4')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
