# Generated by Django 5.0 on 2023-12-09 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='keyboard',
            field=models.BooleanField(verbose_name='Teclado'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='lab_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectors', to='main.laboratory', verbose_name='Laboratorio'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='mouse',
            field=models.BooleanField(verbose_name='Mouse'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='responsible_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='computer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.computer', verbose_name='Computadora'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='capacity',
            field=models.IntegerField(verbose_name='Capacidad'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='cpu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cpu', verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='read_speed',
            field=models.IntegerField(verbose_name='Velocidad de lectura'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='type',
            field=models.CharField(choices=[('ssd', 'SSD'), ('hdd', 'HDD')], max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='write_speed',
            field=models.IntegerField(verbose_name='Velocidad de escritura'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='air_conditioning',
            field=models.BooleanField(verbose_name='Aire acondicionado'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='chair_number',
            field=models.IntegerField(verbose_name='Número de sillas'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='fire_extinguisher',
            field=models.BooleanField(verbose_name='Extintor'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='first_aid_kit',
            field=models.BooleanField(verbose_name='Botiquín de primeros auxilios'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='floor_number',
            field=models.IntegerField(verbose_name='Número de piso'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='projector_screen',
            field=models.BooleanField(verbose_name='Cortina de proyector'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='responsible_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='security_camera',
            field=models.BooleanField(verbose_name='Cámara de seguridad'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='table_number',
            field=models.IntegerField(verbose_name='Número de mesas'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='trash_can',
            field=models.BooleanField(verbose_name='Basurero'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='whiteboard',
            field=models.BooleanField(verbose_name='Pizarra'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='computer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.computer', verbose_name='Computadora'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='herz',
            field=models.CharField(blank=True, choices=[('60', '60'), ('120', '120'), ('144', '144')], max_length=10, null=True, verbose_name='Herz'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='inches',
            field=models.IntegerField(verbose_name='Pulgadas'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='model',
            field=models.CharField(default='', max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='resolution',
            field=models.CharField(max_length=50, verbose_name='Resolución'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='architecture',
            field=models.CharField(choices=[('x86', 'x86'), ('x64', 'x64'), ('X32', 'X32')], max_length=10, verbose_name='Arquitectura'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='cores',
            field=models.IntegerField(verbose_name='Núcleos'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='cpu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cpu', verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='generation',
            field=models.IntegerField(verbose_name='Generación'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='speed',
            field=models.IntegerField(verbose_name='Velocidad'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='threads',
            field=models.IntegerField(verbose_name='Hilos'),
        ),
        migrations.AlterField(
            model_name='projector',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='projector',
            name='lab_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.laboratory', verbose_name='Laboratorio'),
        ),
        migrations.AlterField(
            model_name='projector',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='capacity',
            field=models.IntegerField(verbose_name='Capacidad'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='cpu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cpu', verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='speed',
            field=models.IntegerField(verbose_name='Velocidad'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='type',
            field=models.CharField(choices=[('ddr3', 'DDR3'), ('ddr4', 'DDR4')], max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='computer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.computer', verbose_name='Computadora'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='task',
            name='recommendation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.recommendation', verbose_name='Recomendación'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
