# Generated by Django 5.0 on 2023-12-09 23:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_computer_keyboard_alter_computer_lab_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
    ]
