# Generated by Django 5.0 on 2024-01-03 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_laboratory_air_conditioning_and_more'),
        ('main', '0005_task_status'),
    ]

    operations = [
    ]
