# Generated by Django 5.0 on 2024-01-03 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_merge_20231230_1309'),
        ('main', '0006_merge_20240103_0430'),
    ]

    operations = [
    ]
