# Generated by Django 4.2.7 on 2024-01-06 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_merge_20240103_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('brand', models.CharField(max_length=20, verbose_name='Marca')),
                ('model', models.CharField(max_length=20, verbose_name='Modelo')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
                ('type', models.CharField(choices=[('monitor', 'Monitor'), ('cpu', 'CPU'), ('ram', 'RAM'), ('disk', 'Disco')], max_length=20, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='LabItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('brand', models.CharField(max_length=20, verbose_name='Marca')),
                ('model', models.CharField(max_length=20, verbose_name='Modelo')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
                ('type', models.CharField(choices=[('projector', 'Proyector'), ('security_camera', 'Cámara de seguridad'), ('voltage_regulator', 'Regulador de voltaje'), ('air_conditioner', 'Aire acondicionado')], max_length=20, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Bien de laboratorio',
                'verbose_name_plural': 'Bienes de laboratorio',
            },
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='computer_id',
        ),
        migrations.RemoveField(
            model_name='disk',
            name='cpu_id',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='computer_id',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='cpu_id',
        ),
        migrations.RemoveField(
            model_name='projector',
            name='lab_id',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='cpu_id',
        ),
        migrations.RemoveField(
            model_name='regulator_voltage',
            name='lab_id',
        ),
        migrations.RemoveField(
            model_name='security_camera',
            name='lab_id',
        ),
        migrations.AlterModelOptions(
            name='computer',
            options={'verbose_name': 'Computadora', 'verbose_name_plural': 'Computadoras'},
        ),
        migrations.AlterModelOptions(
            name='laboratory',
            options={'verbose_name': 'Laboratorio', 'verbose_name_plural': 'Laboratorios'},
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'verbose_name': 'Recomendación', 'verbose_name_plural': 'Recomendaciones'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='computer_id',
        ),
        migrations.AddField(
            model_name='computer',
            name='code',
            field=models.CharField(default='C01', max_length=20, unique=True, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name',
            field=models.CharField(default='RECOMENDACION 1', max_length=50, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='TAREA PRUEBA', max_length=50, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='computer',
            name='lab_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computadoras', to='main.laboratory', verbose_name='Laboratorio'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='responsible_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='responsible_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='task',
            name='recommendation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.recommendation', verbose_name='Recomendación'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.DeleteModel(
            name='Air_Conditioner',
        ),
        migrations.DeleteModel(
            name='Cpu',
        ),
        migrations.DeleteModel(
            name='Disk',
        ),
        migrations.DeleteModel(
            name='Monitor',
        ),
        migrations.DeleteModel(
            name='Processor',
        ),
        migrations.DeleteModel(
            name='Projector',
        ),
        migrations.DeleteModel(
            name='Ram',
        ),
        migrations.DeleteModel(
            name='Regulator_voltage',
        ),
        migrations.DeleteModel(
            name='Security_camera',
        ),
        migrations.AddField(
            model_name='labitem',
            name='id_laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.laboratory', verbose_name='Laboratorio'),
        ),
        migrations.AddField(
            model_name='labitem',
            name='responsible_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable'),
        ),
        migrations.AddField(
            model_name='computeritem',
            name='id_computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.computer', verbose_name='Computadora'),
        ),
    ]
