# Generated by Django 4.2.7 on 2024-01-09 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_laboratory_chair_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='id_lab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.laboratory', verbose_name='Laboratorio perteneciente'),
            preserve_default=False,
        ),
    ]
