# Generated by Django 4.2.7 on 2024-01-10 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_recommendation_id_lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='id_lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.laboratory', verbose_name='Laboratorio perteneciente'),
        ),
    ]
