# Generated by Django 4.2.7 on 2024-01-10 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='id_lab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.laboratory', verbose_name='Laboratorio perteneciente'),
            preserve_default=False,
        ),
    ]
